apiVersion: v1
kind: Service
metadata:
  name: {{ include "talos-kms.fullname" . }}
  labels:
    {{- include "talos-kms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "talos-kms.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
